[tool.poetry]
name = "python-hse"
version = "0.1.0"
description = ""
authors = ["Dmitry Kuzmin <dskuzmin@edu.hse.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
